DBENVUSR=`printenv | grep _ENV_MYSQL_USER | sed "s/^.*=//g"`
DBENVPAS=`printenv | grep _ENV_MYSQL_PASS | sed "s/^.*=//g"`
mysql -u$DBENVUSR -p$DBENVPAS -h ${CARBON_MYSQL_DB_HOST} -P ${CARBON_MYSQL_DB_PORT} -e "CREATE DATABASE ${CARBON_APP_NAME}; \
CREATE USER '${CARBON_MYSQL_DB_USERNAME}' IDENTIFIED BY '${CARBON_MYSQL_DB_PASSWORD}'; \
REVOKE ALL PRIVILEGES,GRANT OPTION from ${CARBON_MYSQL_DB_USERNAME}; \
GRANT USAGE ON ${CARBON_APP_NAME}.* to '${CARBON_MYSQL_DB_USERNAME}'@'%' IDENTIFIED BY '${CARBON_MYSQL_DB_PASSWORD}'; \
GRANT ALL PRIVILEGES ON ${CARBON_APP_NAME}.* TO '${CARBON_MYSQL_DB_USERNAME}'@'%' WITH GRANT OPTION; \
FLUSH PRIVILEGES;"
